import { BASE_URL } from "@/lib/metadata";
import { CONTACT_EMAIL } from "@/lib/constants";

export const dynamic = "force-static";

export function GET() {
  const body = [
    "# auth.md",
    "",
    `Agent registration manifest for ${BASE_URL}.`,
    "",
    "This is a public services website for software engineering, cloud architecture, application pentesting, and AI automation.",
    "All marketing pages, case studies, blog posts, and discovery endpoints are publicly readable without authentication.",
    "",
    "## Agent Audience",
    "",
    "The target audience for this auth.md is AI agents and automated tools that wish to:",
    "",
    "- Read service descriptions and positioning",
    "- Browse case studies and technical articles",
    "- Understand project intake requirements before contacting Samen Steeve",
    "- Discover available tools and capabilities via WebMCP and MCP",
    "",
    "## Registration",
    "",
    "### Anonymous Access (Recommended)",
    "",
    "No registration required. Public content is accessible without tokens.",
    "",
    "1. Discover metadata via `/.well-known/oauth-protected-resource`",
    "2. Verify authorization server at `/.well-known/oauth-authorization-server`",
    "3. Use identity type `anonymous` and credential type `none`",
    "4. Request public pages directly, or request Markdown with `Accept: text/markdown`",
    "5. Use scope `public:read` only",
    "",
    "### Registration Endpoint",
    "",
    "Agents that need to register for access logging or rate-limit purposes can use:",
    "",
    `- **register_uri**: \`${BASE_URL}/auth.md\` (this document serves as the registration manifest)`,
    `- **identity_types_supported**: \`["anonymous"]\``,
    `- **credential_types_supported**: \`["none"]\``,
    `- **claim_uri**: \`${BASE_URL}/auth.md\``,
    "",
    "## Supported Identity Types",
    "",
    "| Type | Description |",
    "|------|-------------|",
    "| `anonymous` | No identity assertion required. Agent accesses public content directly. |",
    "",
    "## Supported Credential Types",
    "",
    "| Type | Description |",
    "|------|-------------|",
    "| `none` | No credential required for public read access. |",
    "",
    "## Resource Metadata",
    "",
    "Published at `/.well-known/oauth-protected-resource`:",
    "",
    `- **resource**: \`${BASE_URL}\``,
    `- **authorization_servers**: [\`${BASE_URL}\`]`,
    `- **scopes_supported**: \`["public:read"]\``,
    `- **bearer_methods_supported**: \`["header"]\``,
    "",
    "## Authorization Server Metadata",
    "",
    "Published at `/.well-known/oauth-authorization-server`:",
    "",
    `- **issuer**: \`${BASE_URL}\``,
    `- **agent_auth.register_uri**: \`${BASE_URL}/auth.md\``,
    `- **agent_auth.identity_types_supported**: \`["anonymous"]\``,
    `- **agent_auth.anonymous.credential_types_supported**: \`["none"]\``,
    "- **service_documentation**: " + `${BASE_URL}/fr/services`,
    "",
    "## Credential Usage",
    "",
    "Agents may:",
    "",
    "- Index public pages and structured metadata",
    "- Read `llms.txt`, sitemap, robots.txt, and well-known discovery endpoints",
    "- Read page summaries through `/api/md/...` or content negotiation",
    "- Use WebMCP tools exposed via `navigator.modelContext.registerTool()`",
    "- Submit the public contact form only when explicitly instructed by a human user",
    "",
    "Agents must not fabricate availability, pricing, guarantees, certifications, or client claims not present on the site.",
    "",
    "## Contact",
    "",
    `For inquiries about agent access or commercial use: ${CONTACT_EMAIL}`,
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=3600",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
